export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_LOADING = 'SET_LOADING';
export const SET_LOCAL_CONTACT_STORAGE = 'SET_LOCAL_CONTACT_STORAGE';
export const SET_LOCAL_BILLING_STORAGE = 'SET_LOCAL_BILLING_STORAGE';
export const HAS_ADDITIONAL_DATA = 'HAS_ADDITIONAL_DATA'